services:
  nginx:
    image: nginxinc/nginx-unprivileged:1.27
    container_name: nginx
    user: "1000:1000"
    ports:
      - "80:8080"
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_config/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - ./nginx_config/conf.d:/etc/nginx/conf.d:ro
      - ./nginx_config/common_headers.conf:/etc/nginx/common_headers.conf:ro
      - ./sites:/srv/www:ro
      - ./le_challenges:/var/lib/letsencrypt:ro
      - ./le_certs:/etc/letsencrypt:ro
      - ./nginx_logs:/var/log/nginx/sites
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    user: "1000:1000"
    profiles: ["manual"]
    volumes:
      - ./le_certs:/etc/letsencrypt
      - ./le_challenges:/var/lib/letsencrypt
      - ./le_logs:/var/log/letsencrypt

  node:
    image: node:22
    profiles: ["manual"]
    volumes:
      - ./sites_src:/sites_src
      - /root/.yarn/berry:/root/.yarn/berry
    working_dir: /sites_src

  xray-core:
    image: ghcr.io/xtls/xray-core:25.6.8
    container_name: xray
    cap_add:
      - NET_ADMIN
    ports:
      - "443:4443"
    environment:
      - TZ
    volumes:
      - ./xray_config.jsonc:/usr/local/etc/xray/config.jsonc
      - ./xray_logs:/var/log/xray
    restart: unless-stopped
