- name: Reload systemd daemon
  listen: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart docker service
  listen: restart docker
  ansible.builtin.service:
    state: restarted
    name: docker
